# Generated by Django 3.2.9 on 2021-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.FileField(blank=True, default='', upload_to='')),
                ('url', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
